language: node_js

sudo: true

node_js:
  - "10.14"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - ./scripts/checkSimulationContracts.bash
  - yarn install
  - yarn global add ganache-cli truffle
  - pushd enigma-js && yarn install && popd

before_script:
  - ganache-cli -p 9545 -i 4447 &
  - sleep 5

script:
  - rm -rf build
  - truffle compile
  - truffle migrate --reset --network develop
  - pushd enigma-js && yarn build && popd
  - SGX_MODE=SW truffle migrate --reset --network develop
  - pushd enigma-js && SGX_MODE=SW yarn test && popd
  - git clone https://github.com/enigmampc/discovery-docker-network.git
  - if [[ $TRAVIS_BRANCH == "master" ]]; then export TAG=latest; else export TAG=develop; fi
  - |
    pushd discovery-docker-network &&
    cp .env-template .env &&
    sed -i "s/SGX_MODE=HW/SGX_MODE=SW/" .env &&
    if [[ $TAG == "develop" ]]; then sed -i "s/DOCKER_TAG=latest/DOCKER_TAG=develop/" .env; fi &&
    sed -i "s/-vv/-v/" enigma-core/start_core.bash &&
    popd
  - pushd discovery-docker-network/enigma-contract && docker build --build-arg GIT_BRANCH_CONTRACT=$TRAVIS_BRANCH -t enigmampc/enigma_contract:$TAG --no-cache . && popd
  - pushd discovery-docker-network && docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from client && popd

after_success:
  - pushd enigma-js && yarn report-coverage && popd

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|develop$
